spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cim-test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: zcyzcy159162

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 自动驼峰转换
  type-aliases-package: com.crossoverjie.cim.msg.storage.pojo # 实体类包路径
  global-config:
    db-config:
      id-type: auto