spring:
  application:
    name:
      cim-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cim-test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: c123456

  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
  
# web port
server:
  port: 8081
  
# enable swagger
springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: info

# enable zk
app:
  zk:
    switch: true
    addr: 127.0.0.1:2181
    connect:
      timeout: 30000
    root: /route # zk root path
# cim server config
cim:
  server:
    port: 11211
  route:
    url: http://localhost:8083/ # route url suggested that this is Nginx address
  heartbeat:
    time: 30 # cim heartbeat time(seconds)

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 自动驼峰转换
  type-aliases-package: com.crossoverjie.cim.msg.storage.pojo # 实体类包路径
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

offline:
  store:
    mode: redis_mysql